_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: False  
    NAME: build_resnetdeep_backbone
    # (4)
    FEAT_DIM: 2048       # up to backbone输出维度，resnet=2048
    DEPTH: 101x     #164
    PRETRAIN: False # False
    # PRETRAIN_PATH: /home/my/network-slimming/logs/checkpoint.pth.tar

SOLVER:
  OPT: SGD
  BASE_LR: 0.01  # 0.01
  ETA_MIN_LR: 7.7e-5
  WEIGHT_DECAY: 0.0 # 0.0005

  IMS_PER_BATCH: 32     # 64
  MAX_ITER: 60
  DELAY_ITERS: 30
  WARMUP_EPOCHS: 0   # 10
  FREEZE_ITERS: 10
  MAX_EPOCH: 160

  CHECKPOINT_PERIOD: 5

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

TEST:
  EVAL_PERIOD: 20
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/veri/sbs_R50-deep

PRUNE:
  PERCENT: 0.3
  SAVE_DIR: logs/veri/sbs_R50-ibn/pruned
