_BASE_: ../Base-SBS.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: False  # True
    WITH_NL: False  # True
    NAME: build_resnetx_backbone
    FEAT_DIM: 256       # up to backbone输出维度，resnet=2048
    DEPTH: 56x     #101
    PRETRAIN: False # False

SOLVER:
  OPT: SGD
  BASE_LR: 0.01  # 0.01
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 16  # 64
  MAX_ITER: 60      # 160
  DELAY_ITERS: 30
  WARMUP_EPOCHS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 5 # 20

DATASETS:
  NAMES: ("VeRi",)
  TESTS: ("VeRi",)

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/veri/sbs_R50-x

PRUNE:
  PERCENT: 0.5
  SAVE_DIR: logs/veri/sbs_R50-ibn/pruned
